<ServerApplication xmlns="https://apps-api.moysklad.ru/xml/ns/appstore/app/v2"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="https://apps-api.moysklad.ru/xml/ns/appstore/app/v2 https://apps-api.moysklad.ru/xml/ns/appstore/app/v2/application-v2.xsd">
    <iframe>
        <sourceUrl><?=cfg()->appBaseUrl?>/iframe.php</sourceUrl>
    </iframe>
    <vendorApi>
        <endpointBase><?=cfg()->appBaseUrl?>/vendor-endpoint.php</endpointBase>
    </vendorApi>
    <access>
        <resource><?=cfg()->moyskladJsonApiEndpointUrl?></resource>
        <scope>admin</scope>
    </access>
    <widgets>
        <entity.counterparty.edit>
            <sourceUrl><?=cfg()->appBaseUrl?>/widgets/counterparty-widget.php</sourceUrl>
            <height>
                <fixed>250px</fixed>
            </height>
            <supports>
                <open-feedback/>
            </supports>
        </entity.counterparty.edit>
        <document.customerorder.edit>
            <sourceUrl><?=cfg()->appBaseUrl?>/widgets/customerorder-widget.php</sourceUrl>
            <height>
                <fixed>250px</fixed>
            </height>
            <supports>
                <open-feedback/>
            </supports>
        </document.customerorder.edit>
        <document.demand.edit>
            <sourceUrl><?=cfg()->appBaseUrl?>/widgets/demand-widget.php</sourceUrl>
            <height>
                <fixed>250px</fixed>
            </height>
            <supports>
                <open-feedback/>
            </supports>
        </document.demand.edit>
    </widgets>
    <popups>
        <popup>
            <name>some-popup</name>
            <sourceUrl><?=cfg()->appBaseUrl?>/widgets/popup.php</sourceUrl>
        </popup>
    </popups>
    <buttons>
        <button name="show-notification" title="Отобразить уведомление">
            <locations>
                <document.customerorder.edit/>
                <document.customerorder.list/>
            </locations>
        </button>
        <button name="navigate-to" title="Открыть ссылку">
            <locations>
                <document.customerorder.edit/>
            </locations>
        </button>
        <button name="show-popup" title="Открыть popup">
            <locations>
                <document.customerorder.edit/>
            </locations>
        </button>
    </buttons>
</ServerApplication>
